# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "vclust_align"
description: All-v-all alignments using vclust
keywords:
  - vclust
  - virus
  - align
tools:
  - "vclust":
      description: "Fast and accurate tool for calculating Average Nucleotide Identity (ANI) and clustering virus genomes and metagenomes"
      homepage: "https://github.com/refresh-bio/vclust"
      documentation: "https://github.com/refresh-bio/vclust"
      tool_dev_url: "https://github.com/refresh-bio/vclust"
      doi: "10.1101/2024.06.27.601020"
      licence: ["GNU General Public v3 (GPL v3)"]

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - fasta:
        type: file
        description: Nucleotide sequences FastA file
        pattern: "*.{fasta}"
        ontologies:
          - edam: "http://edamontology.org/format_1929"
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - prefilter:
        type: file
        description: TXT file containing vclust prefilter information
        pattern: "*.txt"
        ontologies:
          - edam: "http://edamontology.org/format_2330"
  - - vclust:
        type: directory
        description: Directory containing vClust's python scripts and binaries
        ontologies:
          - edam: "http://edamontology.org/data_1049"

output:
  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"
  - ani:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "${prefix}.vclust_ani.tsv":
          type: file
          description: TSV file containing vclust ANI information
          ontologies:
            - edam: "http://edamontology.org/format_3475"
  - ids:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "${prefix}.vclust_ani.ids.tsv":
          type: file
          description: TSV file containing vclust ANI IDs
          ontologies:
            - edam: "http://edamontology.org/format_3475"
  - align:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "${prefix}.vclust_align.tsv":
          type: file
          description: TSV file containing vclust alignments
          ontologies:
            - edam: "http://edamontology.org/format_3475"

authors:
  - "@CarsonJM"
maintainers:
  - "@CarsonJM"
