name: "fastq_viromeqc_tsv"
description: Estimate viral enrichment from a FastQ files.
keywords:
  - enrich
  - virome
  - virus
  - phage
components:
  - viromeqc/install
  - viromeqc/viromeqc
input:
  - fastq_gz:
      type: file
      description: |
        The input channel containing FastQ files
        Structure: [ val(meta), [ path(read_1.fastq.gz), path(read_2.fastq.gz) ]
      pattern: "*.{fastq, fastq.gz}"
  - viromeqc_db:
      type: directory
      description: |
        The directory containing viromeQC's indices for read alignment.
        Structure: [ path(viromeqc_db) ]
      pattern: "*.{viromeqc_db}"
output:
  - enrichment_tsv:
      type: file
      description: |
        Channel containing enrichment TSV files.
        Structure: [ val(meta), path(TSV) ]
      pattern: "*.bam"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@CarsonJM"
maintainers:
  - "@CarsonJM"
