name: "checkv_downloaddatabase"
description: Construct the database necessary for checkv's quality assessment
keywords:
  - checkv
  - quality
  - virus
  - completeness
  - contamination
tools:
  - "checkv":
      description: Assess the quality of metagenome-assembled viral genomes.
      homepage: https://bitbucket.org/berkeleylab/checkv/src/master/
      documentation: https://bitbucket.org/berkeleylab/checkv/src/master/
      tool_dev_url: https://bitbucket.org/berkeleylab/checkv/src/master/
      doi: "10.1038/s41587-020-00774-7"
      licence: ["BSD License"]
      identifier: biotools:checkv
output:
  - checkv_db:
      type: directory
      description: directory pointing to database
      pattern: "checkv_db"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@Joon-Klaps"
maintainers:
  - "@Joon-Klaps"
  - "@CarsonJM"
