bump_version: null
lint:
  files_exist:
    - conf/igenomes.config
    - assets/multiqc_config.yml
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - docs/output.md
    - docs/README.md
    - docs/usage.md
    - assets/multiqc_config.yml
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - docs/output.md
    - docs/README.md
    - docs/usage.md
    - CODE_OF_CONDUCT.md
    - assets/nf-core-toolkit_logo_light.png
    - docs/images/nf-core-toolkit_logo_light.png
    - docs/images/nf-core-toolkit_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-toolkit_logo_light.png
    - docs/images/nf-core-toolkit_logo_light.png
    - docs/images/nf-core-toolkit_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config: false
  nextflow_config:
    - process.cpus
    - process.memory
    - process.time
    - custom_config
    - params.custom_config_version
    - params.custom_config_base
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
nf_core_version: 3.0.0.dev0
org_path: null
repository_type: pipeline
template:
  author: CarsonJM
  description: A Nextflow pipeline for running microbe-related analyses
  force: false
  is_nfcore: false
  name: toolkit
  org: nf-microbe
  outdir: .
  skip_features:
    - nf_core_configs
    - multiqc
    - fastqc
    - email
    - adaptivecard
    - slackreport
    - documentation
    - seqera_platform
  version: 1.0.0dev
update: null
