# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "seqhasher_seqhasher"
description: Compute hash digests for DNA sequences in a FASTA file
keywords:
  - hash
  - sequence
  - kmer
tools:
  - "seqhasher":
      description: "Compute hash digests for DNA sequences in a FASTA file"
      homepage: "https://github.com/apcamargo/seq-hasher"
      documentation: "https://github.com/apcamargo/seq-hasher"
      tool_dev_url: "https://github.com/apcamargo/seq-hasher"
      licence: ["MIT"]

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - fasta:
        type: file
        description: FastA file
        pattern: "*.{fasta}.*"
        ontologies:
          - edam: "http://edamontology.org/format_1929"
  - - seq_hasher:
        type: file
        description: |
          Path to compiled seq-hasher executable

output:
  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"
  - tsv:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "${prefix}.seq-hasher.tsv":
          type: file
          description: Output TSV containing sequence hash digests
          ontologies:
            - edam: "http://edamontology.org/format_3475"

authors:
  - "@CarsonJM"
maintainers:
  - "@CarsonJM"
