# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "trtrimmer"
description: Identify and trim terminal repeats from sequences in FASTA files
keywords:
  - trim
  - terminal repeat
  - fasta
tools:
  - "trtrimmer":
      description: "Identify and trim terminal repeats from sequences in FASTA files"
      homepage: "https://github.com/apcamargo/tr-trimmer"
      documentation: "https://github.com/apcamargo/tr-trimmer"
      tool_dev_url: "https://github.com/apcamargo/tr-trimmer"
      licence: ["MIT"]

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - fasta:
        type: file
        description: FastA file
        pattern: "*.{fasta}.*"
        ontologies:
          - edam: "http://edamontology.org/format_1929"
  - - tr_trimmer:
        type: file
        description: |
          Path to compiled tr-trimmer executable

output:
  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"
  - fasta:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "${prefix}.tr-trimmer.fasta.gz":
          type: file
          description: Output FastA file containing TR-removed sequences.
          ontologies:
            - edam: "http://edamontology.org/format_1929"

authors:
  - "@CarsonJM"
maintainers:
  - "@CarsonJM"
