name: "plass_penguin"
description: Protein-guided nucleotide assembly
keywords:
  - assembly
  - contigs
  - scaffolds
tools:
  - "plass":
      description: "Plass (Protein-Level ASSembler) is a software to assemble short read sequencing data on a protein level"
      homepage: "https://github.com/soedinglab/plass"
      documentation: "https://github.com/soedinglab/plass"
      tool_dev_url: "https://github.com/soedinglab/plass"
      doi: "10.1038/s41592-019-0437-4"
      licence: ["GPL v3"]
  - "penguin":
      description: "PenguiN - Protein-guided Nucleotide assembler"
      homepage: "https://github.com/soedinglab/plass"
      documentation: "https://github.com/soedinglab/plass"
      tool_dev_url: "https://github.com/soedinglab/plass"
      doi: "10.1101/2024.03.29.587318"
      licence: ["GPL v3"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - fastq:
      type: file
      description: |
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively in gzipped or uncompressed FASTQ or FASTA format.
      pattern: "*.{fastq.gz, fastq}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - contigs:
      type: file
      description: Assembled contigs in FastA format.
      pattern: "*.fasta.gz"
  - log:
      type: file
      description: Log file output by penguin
      pattern: "*.penguin.log"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@CarsonJM"
maintainers:
  - "@CarsonJM"
