# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "pyhmmer_buscoclassify"
description: Classify cellular sequences using additional HMMs
keywords:
  - hmm
  - pyhmmer
  - busco
  - bacteria
  - archaea
tools:
  - "pyhmmer":
      description: "Cython bindings and Python interface to HMMER3."
      homepage: "https://pyhmmer.readthedocs.io"
      documentation: "https://pyhmmer.readthedocs.io"
      tool_dev_url: "https://github.com/althonos/pyhmmer"
      doi: 10.1093/bioinformatics/btad214
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - faa:
      type: file
      description: Protein sequences in translated FastA format.
      pattern: "*.{fasta,faa}.gz"
  - archaea_hmms:
      type: file
      description: HMMs for identifying  archaeal proteins.
      pattern: "*.hmm"
  - archaea_cutoffs:
      type: file
      description: Cutoffs for identifying archaeal proteins.
      pattern: "*.cutoffs"
  - bacteria_hmms:
      type: file
      description: HMMs for identifying bacterial proteins.
      pattern: "*.hmm"
  - bacteria_cutoffs:
      type: file
      description: Cutoffs for identifying bacterial proteins.
      pattern: "*.cutoffs"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - hits:
      type: file
      description: Pyhmmer output after searching against all BUSCO HMMs.
      pattern: "*.busco_hmms.tsv"
  - markers:
      type: file
      description: Parsed Pyhmmer output containing hallmark counts and hits for each sequences.
      pattern: "*.busco_markers.tsv"

authors:
  - "@CarsonJM"
maintainers:
  - "@CarsonJM"
