# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "fasta_genomad_fastatsv"
description: Predict and annotate virus/plasmid sequences.
keywords:
  - virus
  - plasmid
  - prediction
  - genomad
components:
  - genomad/download
  - genomad/endtoend

input:
  - fasta_gz:
      type: file
      description: |
        The input channel containing the FastA files
        Structure: [ val(meta), path(fasta.gz) ]
      pattern: "*.{fasta,fna,fa,fasta.gz,fna.gz,fa.gz}"

output:
  - plasmid_fasta:
      type: file
      description: FASTA file containing predicted plasmid sequences
      pattern: "*_plasmid.fna.gz"
  - plasmid_proteins:
      type: file
      description: FASTA file containing predicted plasmid protein sequences
      pattern: "*_plasmid_proteins.faa.gz"
  - plasmid_summary:
      type: file
      description: TSV file containing a summary of geNomad's plasmid predictions
      pattern: "*_plasmid_summary.tsv"
  - virus_fasta:
      type: file
      description: FASTA file containing predicted virus sequences
      pattern: "*_virus.fna.gz"
  - virus_proteins:
      type: file
      description: FASTA file containing predicted virus protein sequences
      pattern: "*_virus_proteins.faa.gz"
  - virus_summary:
      type: file
      description: TSV file containing a summary of geNomad's virus predictions
      pattern: "*_virus_summary.tsv"
  - proteins:
      type: file
      description: FAA file containing predicted protein sequences
      pattern: "*_proteins.faa.gz"
  - genes:
      type: file
      description: Detailed output of geNomad's marker gene classification.
      pattern: "*_genes.tsv"
  - features:
      type: file
      description: Detailed output of geNomad's feature analysis
      pattern: "*_features.tsv"
  - aggregated_classification:
      type: file
      description: Combined classification scores for each contig/scaffold/chromosome
      pattern: "*_aggregated_classification.tsv"
  - taxonomy:
      type: file
      description: Detailed output of geNomad's marker gene taxonomy analysis
      pattern: "*_taxonomy.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@CarsonJM"
maintainers:
  - "@CarsonJM"
