name: "viromeqc_install"
description: Download ViromeQC's indices for read alignment
keywords:
  - virome
  - enrichment
  - phage
  - virus
tools:
  - "viromeqc":
      description: |
        ViromeQC is a computational tool to benchmark and quantify non-viral contamination in VLP-enrihed viromes. ViromeQC
        provides an enrichment score for each virome. The score is calculated with respect to the expected prokaryotic markers
        abundances in reference metagenomes
      homepage: "https://github.com/SegataLab/viromeqc"
      documentation: "https://github.com/SegataLab/viromeqc"
      tool_dev_url: "https://github.com/SegataLab/viromeqc"
      doi: "10.1038/s41587-019-0334-5"
      licence: ["MIT"]

output:
  - viromeqc_db:
      - "viromeqc_db/":
        type: directory
        description: Directory containing viromeQC's indices for read alignment.
        pattern: "viromeqc_db/"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@CarsonJM"
maintainers:
  - "@CarsonJM"
