channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bowtie2=2.3.4
  - bioconda::diamond=0.9.29
  - bioconda::pysam=0.19.1
  - bioconda::samtools=1.3.1
  - conda-forge::biopython=1.79
  - conda-forge::pandas=0.20
  - conda-forge::python=3.6
