# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::blast=2.16.0
  - bioconda::bwa=0.7.18
  - bioconda::sambamba=1.0.1
  - bioconda::samtools=1.21
  - conda-forge::gawk=5.3.1
