---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "custom_cleanworkdirs"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::nextflow=24.04.4"
