# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "fasta_vclust_fasta"
description: Align and cluster sequences in a FastA file
keywords:
  - virus
  - plasmid
  - cluster
  - align
components:
  - seqhasher/sequniq
  - seqkit/grep
  - vclust/align
  - vclust/cluster
  - vclust/prefilter

input:
  - fasta_gz:
      type: file
      description: |
        The input channel containing the FastA files
        Structure: [ val(meta), path(fasta.gz) ]
      pattern: "*.{fasta,fna,fa,fasta.gz,fna.gz,fa.gz}"

output:
  - cluster_reps_fasta_gz:
      type: file
      description: |
        Channel containing the representative sequences of each cluster
        Structure: [ val(meta), path(fasta.gz) ]
      pattern: "*.fasta.gz"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"

authors:
  - "@CarsonJM"
maintainers:
  - "@CarsonJM"
