# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "pyrodigalgv"
description: Predict genes in viruses and viruses with alternative genetic codes.
keywords:
  - virus
  - genes
  - prodigal
  - phage
  - pyrodigal
tools:
  - "pyrodigalgv":
      description: "A Pyrodigal extension to predict genes in giant viruses and viruses with alternative genetic code."
      homepage: "https://github.com/althonos/pyrodigal-gv"
      documentation: "https://github.com/althonos/pyrodigal-gv"
      tool_dev_url: "https://github.com/althonos/pyrodigal-gv"
      licence: ["GPL v3-or-later"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - fasta:
      type: file
      description: Input nucleotide sequences in FastA format.
      pattern: "*.{fasta,fa,fna}.gz"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - gff:
      type: file
      description: Predicted genes in GFF format.
      pattern: "*.pyrodigalgv.gff.gz"
  - faa:
      type: file
      description: Translated sequences for predicted genes in protein FastA format.
      pattern: "*.pyrodigalgv.faa.gz"
  - fna:
      type: file
      description: Nucleotide sequences for predicted genes in FastA format.
      pattern: "*.pyrodigalgv.fna.gz"

authors:
  - "@CarsonJM"
maintainers:
  - "@CarsonJM"
