# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "UTILS_NFMICROBE_FUNCTIONS"
description: Subworkflow with utility functions specific to the nf-microbe subworkflows and pipelines
keywords:
  - utility
  - pipeline
  - empty
  - clean
  - nf-microbe
components: []
output:
  - success:
      type: boolean
      description: |
        Dummy output to indicate success
authors:
  - "@CarsonJM"
maintainers:
  - "@CarsonJM"
